### ISSUE TITLE
Looks like it does not work with AngularJS v1.4.8

### ISSUE THREAD

**Issue by Timur-P** [shagstrom/angular-split-pane#5]
I tried example from readme, and it does not work. :(

**Comment by shagstrom** [comment]
Can you be a bit more specific?

I just tried it and it work for me.

Make sure that the script and stylesheet paths matches your setup.

I have updated the readme example to be a bit more clear.

**Comment by shagstrom** [comment]
You can also clone the project and try the examples from the source code.
