### ISSUE TITLE
How do I programmatically change pane height? 

### ISSUE THREAD

**Issue by jmuronis** [shagstrom/angular-split-pane#6]
Is there a way I can expose a function in the directive to alter the height or width of one of the panes?

I've seen an example for the jquery version of this but I'm looking for an angular solution. Thanks.

**Comment by shagstrom** [comment]
I have not implemented that in angular-split-pane, yet. It's high on the priority list, though. In the meantime I guess you'll have to do this $(selector).splitPane('firstComponentSize', 0). Not very angular, I know, but it works.

**Comment by jmuronis** [comment]
No problem. That is the route I ended up taking (was able to find this suggestion on the jQuery implementation). Thanks for making this, btw!
