### ISSUE TITLE
What version of `split-pane` are you using?

### ISSUE THREAD

**Issue by OoDeLally** [shagstrom/angular-split-pane#9]
I am trying to use the pane splitter with `data-split-pane-properties`.

On resize, I get an error:

`Cannot read property 'firstComponentSize' of undefined` in https://github.com/shagstrom/angular-split-pane/blob/master/angular-split-pane.js#L80

`splitPaneProperties` is not set.

The reason is that the version of `split-pane` we can find on bower or github doesnt send `splitPaneProperties` as extra data on triggering `splitpaneresize`:

```
$splitPane.trigger('splitpaneresize');
```

I checked the version you use in your demo (http://www.dreamchain.com/static/angular-split-pane/bower_components/split-pane/split-pane.js)

```
$splitPane.trigger('splitpaneresize', [ getComponentsSizes($splitPane) ]);
```

Your file indicates `Split Pane v0.9.2`

The version `v0.9.2` I can find on bower/github doesnt have that.

Did you manually customize that file, or is there a hidden location I can find that file on bower?

Thank you

**Comment by MartijnWelker** [comment]
Having the same issue, looks like we have to patch this ourselves

**Comment by shagstrom** [comment]
Try the latest version. I just did this:

    machine:removeme simon$ bower install --save-dev angular-split-pane
    bower angular-split-pane#*  not-cached https://github.com/shagstrom/angular-split-pane.git#*
    bower angular-split-pane#*     resolve https://github.com/shagstrom/angular-split-pane.git#*
    bower angular-split-pane#*    checkout 1.3.1
    bower angular-split-pane#*    resolved https://github.com/shagstrom/angular-split-pane.git#1.3.1
    bower angular#^1.2.0            cached https://github.com/angular/bower-angular.git#1.6.1
    bower angular#^1.2.0          validate 1.6.1 against https://github.com/angular/bower-angular.git#^1.2.0
    bower split-pane#0.9.3          cached https://github.com/shagstrom/split-pane.git#0.9.3
    bower split-pane#0.9.3        validate 0.9.3 against https://github.com/shagstrom/split-pane.git#0.9.3
    bower jquery#~1.11.1            cached https://github.com/jquery/jquery-dist.git#1.11.3
    bower jquery#~1.11.1          validate 1.11.3 against https://github.com/jquery/jquery-dist.git#~1.11.1
    bower angular-split-pane#^1.3.1          install angular-split-pane#1.3.1
    bower split-pane#0.9.3                   install split-pane#0.9.3
    bower angular#^1.2.0                     install angular#1.6.1
    bower jquery#~1.11.1                     install jquery#1.11.3
    bower                                    no-json No bower.json file to save to, use bower init to create one
    
    angular-split-pane#1.3.1 bower_components/angular-split-pane
    ├── angular#1.6.1
    └── split-pane#0.9.3
    
    split-pane#0.9.3 bower_components/split-pane
    └── jquery#1.11.3
    
    angular#1.6.1 bower_components/angular
    
    jquery#1.11.3 bower_components/jquery
    machine:removeme simon$ subl index.html
    machine:removeme simon$ php -S localhost:7000
    PHP 5.5.38 Development Server started at Wed Feb  1 09:42:23 2017
    Listening on http://localhost:7000


This the following index.html

    <html>
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
            <title>Fixed left</title>
            <link rel="stylesheet" href="../bower_components/split-pane/split-pane.css" />
            <script src="../bower_components/jquery/dist/jquery.min.js"></script>
            <script src="../bower_components/angular/angular.js"></script>
            <script src="../bower_components/split-pane/split-pane.js"></script>
            <script src="../bower_components/angular-split-pane/angular-split-pane.js"></script>
            <style type="text/css">
                html, body { height: 100%; min-height: 100%; margin: 0; padding: 0; }
                /* The styling bolow is very simple. You can style things your own way. */
                body { box-sizing: border-box; background: #aaa; padding: 5px; }
                .split-pane-divider { background: #aaa; }
                .split-pane-component { background: #fff; }
            </style>
        </head>
        <body data-ng-app="example" ng-controller="MainCtrl">
            <div data-split-pane data-split-pane-properties="splitPaneProperties">
                <div data-split-pane-component data-width="20em">
                    <p>Left</p>
                    <p>
                        {{splitPaneProperties}}
                        <button data-ng-click="setLastComponent(0)">Collapse right component</button>
                    </p>
                    <p>Left component size {{splitPaneProperties.firstComponentSize}}px</p>
                    <p>Right component size {{splitPaneProperties.lastComponentSize}}px</p>
                </div>
                <div data-split-pane-divider data-width="5px"></div>
                <div data-split-pane-component>
                    <p>Right</p>
                    <p>
                        <button data-ng-click="setFirstComponent(0)">Collapse left component</button>
                    </p>
                    <p>Left component size {{splitPaneProperties.firstComponentSize}}px</p>
                    <p>Right component size {{splitPaneProperties.lastComponentSize}}px</p>
                </div>
            </div>
            <script>
                angular.module('example', ['shagstrom.angular-split-pane'])
                .controller('MainCtrl', function ($scope) {
                    $scope.splitPaneProperties = {};
                    $scope.setFirstComponent = function (value) {
                        $scope.splitPaneProperties.firstComponentSize = value;
                    };
                    $scope.setLastComponent = function (value) {
                        $scope.splitPaneProperties.lastComponentSize = value;
                    };
                });
            </script>
        </body>
    </html>

**Comment by shagstrom** [comment]
Alright, check out v.1.3.2.
